name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: 20

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build --stacktrace
