name: Check Dependencies Updates

on:
  schedule:
    - cron: 40 1 * * *

jobs:

  build:
    name: 🔭 Check for dependencies update
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew dependencyUpdates --stacktrace
